### ISSUE TITLE
Add warning about LocalIn/Out UGens used internally

### ISSUE THREAD

**Issue by mtmccrea** [JamesWenlock/AmbiVerbSC#2]
Hi James (and @joslloand, fyi), 

I was digging though the docs on Writing Unit Generators (in SC Help system), and came across a note about SynthDefs:

> A SynthDef can only have two LocalIn/LocalOut pairings — one for control rate and one for audio rate. Putting LocalIn and LocalOut in a pseudo-UGen is a bad idea, as it could interfere with other feedback loops in the SynthDef.

You may have come across this before and the results can be bad and hard to debug...

I don't necessarily agree that it's a bad idea to have it in a pseudo-ugen ... but because this reverb is a pseudo-ugen and uses LocalIn/Out internally, it would be a good idea to make a "Warning" in the help file and tutorial file that this is the case and so the SynthDef that uses it shouldn't have another instance of LocalIn/Out in it.

**Comment by JamesWenlock** [comment]
Thanks mike! I'll add it!
